import { useState } from 'react'
import {
  GitPullRequest,
  CheckCircle2,
  GitBranch,
  GitCommit,
  ExternalLink,
  Loader2,
  AlertOctagon,
  ArrowRight,
  ShieldCheck,
  FileCode2,
} from 'lucide-react'
import { api } from '../services/api'
import { useApp } from '../contexts/AppContext'
import { useNavigate } from 'react-router-dom'

const STEPS = [
  { id: 'branch', label: 'Create Branch' },
  { id: 'commit', label: 'Commit Fix' },
  { id: 'pr', label: 'Open Pull Request' },
]

export default function PullRequestsPage() {
  const navigate = useNavigate()
  const {
    selectedRepo,
    selectedFinding,
    generatedFix,
    validatedFix,
  } = useApp()

  // Workflow state
  const [branchName, setBranchName] = useState(
    selectedFinding
      ? `codesentinel/fix-${(selectedFinding.title || 'issue').toLowerCase().replace(/\s+/g, '-').slice(0, 40)}`
      : 'codesentinel/fix'
  )
  const [prTitle, setPrTitle] = useState(
    selectedFinding ? `fix: ${selectedFinding.title || 'security issue'}` : 'fix: CodeSentinel AI fix'
  )
  const [prBody, setPrBody] = useState(
    [
      '## CodeSentinel AI Fix',
      '',
      selectedFinding ? `**Issue:** ${selectedFinding.title || selectedFinding.description || ''}` : '',
      selectedFinding?.file ? `**File:** \`${selectedFinding.file}\`` : '',
      generatedFix?.explanation ? `\n**Explanation:** ${generatedFix.explanation}` : '',
      '',
      '> This pull request was generated by CodeSentinel AI. Please review before merging.',
    ].filter((l) => l !== undefined).join('\n').trim()
  )

  // Step results
  const [branchResult, setBranchResult] = useState(null)
  const [commitResult, setCommitResult] = useState(null)
  const [prResult, setPrResult] = useState(null)

  // Loading + error per step
  const [branchLoading, setBranchLoading] = useState(false)
  const [commitLoading, setCommitLoading] = useState(false)
  const [prLoading, setPrLoading] = useState(false)

  const [branchError, setBranchError] = useState(null)
  const [commitError, setCommitError] = useState(null)
  const [prError, setPrError] = useState(null)

  // Determine current step
  const currentStep = !branchResult ? 'branch' : !commitResult ? 'commit' : !prResult ? 'pr' : 'done'

  // Guard: no repo
  if (!selectedRepo) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] text-center space-y-4">
        <GitBranch className="w-12 h-12 text-ink-tertiary opacity-30" />
        <h2 className="text-lg font-semibold text-ink-primary">No repository selected</h2>
        <button onClick={() => navigate('/repositories')} className="px-5 py-2.5 text-sm font-semibold rounded-xl bg-accent-teal/20 text-accent-teal transition-all">
          Go to Repositories
        </button>
      </div>
    )
  }

  const fixContent = validatedFix?.fixed_code || generatedFix?.fixed_code || generatedFix?.suggested_fix || ''
  const filePath = selectedFinding?.file || ''

  // Step 1: Create Branch
  const handleCreateBranch = async () => {
    setBranchLoading(true)
    setBranchError(null)
    try {
      const result = await api.createBranch(
        selectedRepo.owner,
        selectedRepo.repo,
        branchName,
        selectedRepo.default_branch
      )
      setBranchResult(result)
    } catch (err) {
      setBranchError(err.message || 'Failed to create branch.')
    } finally {
      setBranchLoading(false)
    }
  }

  // Step 2: Commit
  const handleCommit = async () => {
    setCommitLoading(true)
    setCommitError(null)
    try {
      const result = await api.createCommit(
        selectedRepo.owner,
        selectedRepo.repo,
        branchName,
        filePath,
        fixContent,
        `fix: ${selectedFinding?.title || 'apply CodeSentinel AI fix'} [CodeSentinel AI]`
      )
      setCommitResult(result)
    } catch (err) {
      setCommitError(err.message || 'Failed to commit.')
    } finally {
      setCommitLoading(false)
    }
  }

  // Step 3: Pull Request
  const handleOpenPR = async () => {
    setPrLoading(true)
    setPrError(null)
    try {
      const result = await api.createPullRequest(
        selectedRepo.owner,
        selectedRepo.repo,
        prTitle,
        branchName,
        selectedRepo.default_branch,
        prBody
      )
      setPrResult(result)
    } catch (err) {
      setPrError(err.message || 'Failed to create pull request.')
    } finally {
      setPrLoading(false)
    }
  }

  const stepStatus = (stepId) => {
    if (stepId === 'branch') return branchResult ? 'done' : branchLoading ? 'loading' : currentStep === 'branch' ? 'current' : 'pending'
    if (stepId === 'commit') return commitResult ? 'done' : commitLoading ? 'loading' : currentStep === 'commit' ? 'current' : 'pending'
    if (stepId === 'pr') return prResult ? 'done' : prLoading ? 'loading' : currentStep === 'pr' ? 'current' : 'pending'
    return 'pending'
  }

  return (
    <div className="space-y-6 pb-12 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-surface-border/50">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2 py-0.5 rounded-full bg-surface-border text-ink-tertiary text-[10px] font-mono uppercase tracking-wider">
              GitHub Workflow
            </span>
          </div>
          <h1 className="text-2xl font-bold text-ink-primary tracking-tight">
            Create Pull Request
          </h1>
          <p className="text-xs text-ink-secondary mt-1">
            {selectedRepo.full_name} · branch from <span className="font-mono text-accent-teal">{selectedRepo.default_branch}</span>
          </p>
        </div>
      </div>

      {/* Validation warning if no validated fix */}
      {!validatedFix && fixContent && (
        <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-start gap-3">
          <AlertOctagon className="w-5 h-5 shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-sm">Fix not validated</p>
            <p className="text-xs mt-0.5 text-amber-300/80">
              The fix has not been validated by the backend. We recommend validating before committing.{' '}
              <button onClick={() => navigate('/fixes')} className="underline hover:text-amber-300">
                Go to Fixes page
              </button>
            </p>
          </div>
        </div>
      )}

      {!fixContent && (
        <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-start gap-3">
          <AlertOctagon className="w-5 h-5 shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-sm">No fix content available</p>
            <p className="text-xs mt-0.5 text-amber-300/80">
              Generate and validate a fix first.{' '}
              <button onClick={() => navigate('/fixes')} className="underline hover:text-amber-300">
                Go to Fixes page
              </button>
            </p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Timeline */}
        <div className="lg:col-span-4">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-ink-tertiary mb-6">
            Workflow Steps
          </h2>
          <div className="relative">
            <div className="absolute left-[15px] top-4 bottom-6 w-0.5 bg-surface-border/60" />
            <div className="space-y-6 relative">
              {STEPS.map((step) => {
                const s = stepStatus(step.id)
                return (
                  <div key={step.id} className="flex gap-4">
                    <div className="relative z-10">
                      {s === 'done' ? (
                        <div className="w-8 h-8 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
                          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                        </div>
                      ) : s === 'loading' ? (
                        <div className="w-8 h-8 rounded-full bg-accent-cyan/10 border border-accent-cyan/30 flex items-center justify-center">
                          <Loader2 className="w-4 h-4 animate-spin text-accent-cyan" />
                        </div>
                      ) : s === 'current' ? (
                        <div className="w-8 h-8 rounded-full bg-accent-violet/20 border border-accent-violet/40 flex items-center justify-center">
                          <div className="w-2.5 h-2.5 rounded-full bg-accent-violet animate-pulse" />
                        </div>
                      ) : (
                        <div className="w-8 h-8 rounded-full bg-surface-base border border-surface-border/80 flex items-center justify-center">
                          <div className="w-2 h-2 rounded-full bg-surface-border" />
                        </div>
                      )}
                    </div>
                    <div className={`flex flex-col justify-center pt-1.5 ${
                      s === 'done' ? 'text-ink-secondary' :
                      s === 'current' || s === 'loading' ? 'text-ink-primary font-semibold' :
                      'text-ink-tertiary'
                    }`}>
                      <span className="text-sm">{step.label}</span>
                      {s === 'current' && (
                        <span className="text-[10px] uppercase tracking-wider text-accent-violet mt-0.5">
                          Next Action
                        </span>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        </div>

        {/* Action panel */}
        <div className="lg:col-span-8 space-y-4">

          {/* Step 1: Branch */}
          <div className={`p-5 rounded-2xl bg-surface-card border transition-all ${
            currentStep === 'branch' || branchResult ? 'border-surface-border' : 'border-surface-border/40 opacity-50'
          }`}>
            <div className="flex items-center gap-2 mb-3">
              <GitBranch className="w-4 h-4 text-accent-cyan" />
              <h3 className="text-sm font-semibold text-ink-primary">Step 1 — Create Branch</h3>
              {branchResult && <CheckCircle2 className="w-4 h-4 text-emerald-400 ml-auto" />}
            </div>

            {!branchResult && (
              <>
                <label className="block text-xs text-ink-tertiary mb-1">Branch name</label>
                <input
                  type="text"
                  value={branchName}
                  onChange={(e) => setBranchName(e.target.value)}
                  className="w-full px-3 py-2 text-xs font-mono rounded-lg bg-surface-base border border-surface-border text-ink-primary focus:outline-none focus:border-accent-cyan/50 mb-3"
                />
                <p className="text-[10px] text-ink-tertiary mb-3">
                  Base: <span className="font-mono text-accent-teal">{selectedRepo.default_branch}</span>
                </p>
                <button
                  onClick={handleCreateBranch}
                  disabled={branchLoading || !branchName}
                  className="px-4 py-2 text-xs font-semibold rounded-xl bg-accent-violet hover:bg-accent-violet/90 disabled:opacity-60 text-white transition-all flex items-center gap-2"
                >
                  {branchLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <GitBranch className="w-4 h-4" />}
                  {branchLoading ? 'Creating…' : 'Create Branch'}
                </button>
              </>
            )}

            {branchResult && (
              <p className="text-xs font-mono text-emerald-400">
                ✓ Branch <span className="text-accent-cyan">{branchName}</span> created successfully.
              </p>
            )}

            {branchError && (
              <div className="mt-2 p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-xs flex items-center gap-2">
                <AlertOctagon className="w-4 h-4 shrink-0" />
                {branchError}
              </div>
            )}
          </div>

          {/* Step 2: Commit */}
          <div className={`p-5 rounded-2xl bg-surface-card border transition-all ${
            currentStep === 'commit' || commitResult ? 'border-surface-border' : 'border-surface-border/40 opacity-50'
          }`}>
            <div className="flex items-center gap-2 mb-3">
              <GitCommit className="w-4 h-4 text-accent-violet" />
              <h3 className="text-sm font-semibold text-ink-primary">Step 2 — Commit Fix</h3>
              {commitResult && <CheckCircle2 className="w-4 h-4 text-emerald-400 ml-auto" />}
            </div>

            {branchResult && !commitResult && (
              <>
                <div className="space-y-2 mb-3">
                  <div className="flex items-center gap-2 text-xs text-ink-secondary">
                    <FileCode2 className="w-3.5 h-3.5 text-ink-tertiary" />
                    <span>File: <span className="font-mono text-accent-cyan">{filePath || '(not specified)'}</span></span>
                  </div>
                  {!fixContent && (
                    <p className="text-xs text-amber-400">⚠ No fix content available. Generate a fix first.</p>
                  )}
                  {fixContent && (
                    <div className="p-2 rounded-lg bg-surface-base border border-surface-border max-h-32 overflow-y-auto">
                      <pre className="text-[10px] font-mono text-ink-secondary">{fixContent.slice(0, 500)}{fixContent.length > 500 ? '\n…' : ''}</pre>
                    </div>
                  )}
                </div>
                <button
                  onClick={handleCommit}
                  disabled={commitLoading || !fixContent || !filePath}
                  className="px-4 py-2 text-xs font-semibold rounded-xl bg-accent-violet hover:bg-accent-violet/90 disabled:opacity-60 text-white transition-all flex items-center gap-2"
                >
                  {commitLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <GitCommit className="w-4 h-4" />}
                  {commitLoading ? 'Committing…' : 'Commit to Branch'}
                </button>
              </>
            )}

            {commitResult && (
              <div className="text-xs space-y-1">
                <p className="text-emerald-400">✓ Committed successfully.</p>
                {commitResult.sha && (
                  <p className="font-mono text-ink-tertiary">SHA: <span className="text-ink-secondary">{commitResult.sha}</span></p>
                )}
              </div>
            )}

            {commitError && (
              <div className="mt-2 p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-xs flex items-center gap-2">
                <AlertOctagon className="w-4 h-4 shrink-0" />
                {commitError}
              </div>
            )}
          </div>

          {/* Step 3: PR */}
          <div className={`p-5 rounded-2xl bg-surface-card border transition-all ${
            currentStep === 'pr' || prResult ? 'border-surface-border' : 'border-surface-border/40 opacity-50'
          }`}>
            <div className="flex items-center gap-2 mb-3">
              <GitPullRequest className="w-4 h-4 text-accent-teal" />
              <h3 className="text-sm font-semibold text-ink-primary">Step 3 — Open Pull Request</h3>
              {prResult && <CheckCircle2 className="w-4 h-4 text-emerald-400 ml-auto" />}
            </div>

            {commitResult && !prResult && (
              <>
                <div className="space-y-3 mb-3">
                  <div>
                    <label className="block text-xs text-ink-tertiary mb-1">PR Title</label>
                    <input
                      type="text"
                      value={prTitle}
                      onChange={(e) => setPrTitle(e.target.value)}
                      className="w-full px-3 py-2 text-xs font-mono rounded-lg bg-surface-base border border-surface-border text-ink-primary focus:outline-none focus:border-accent-cyan/50"
                    />
                  </div>
                  <div>
                    <label className="block text-xs text-ink-tertiary mb-1">PR Body</label>
                    <textarea
                      value={prBody}
                      onChange={(e) => setPrBody(e.target.value)}
                      rows={4}
                      className="w-full px-3 py-2 text-xs font-mono rounded-lg bg-surface-base border border-surface-border text-ink-primary focus:outline-none focus:border-accent-cyan/50 resize-none"
                    />
                  </div>
                  <div className="flex gap-4 text-xs text-ink-tertiary">
                    <span>Head: <span className="font-mono text-accent-cyan">{branchName}</span></span>
                    <span>Base: <span className="font-mono text-accent-teal">{selectedRepo.default_branch}</span></span>
                  </div>
                </div>
                <button
                  onClick={handleOpenPR}
                  disabled={prLoading || !prTitle}
                  className="px-4 py-2.5 text-xs font-semibold rounded-xl bg-accent-teal hover:bg-accent-teal/90 disabled:opacity-60 text-surface-950 transition-all flex items-center gap-2"
                >
                  {prLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <GitPullRequest className="w-4 h-4" />}
                  {prLoading ? 'Opening PR…' : 'Open Pull Request'}
                  {!prLoading && <ArrowRight className="w-3.5 h-3.5" />}
                </button>
              </>
            )}

            {prResult && (
              <div className="space-y-3">
                <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <p className="font-semibold text-emerald-400 text-sm">Pull Request Created!</p>
                    {prResult.number && (
                      <p className="text-xs text-ink-secondary mt-0.5">
                        PR #{prResult.number}
                        {prResult.title && ` · "${prResult.title}"`}
                      </p>
                    )}
                  </div>
                </div>
                {prResult.html_url && (
                  <a
                    href={prResult.html_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-full py-2.5 text-xs font-semibold rounded-xl bg-surface-border hover:bg-surface-border/80 text-ink-primary hover:text-accent-cyan transition-all flex items-center justify-center gap-2"
                  >
                    <ExternalLink className="w-4 h-4" />
                    View PR #{prResult.number} on GitHub
                  </a>
                )}
                <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/20 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-amber-400 shrink-0" />
                  <p className="text-xs text-amber-300">
                    Please review the changes before merging. CodeSentinel AI does not auto-merge.
                  </p>
                </div>
              </div>
            )}

            {prError && (
              <div className="mt-2 p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-xs flex items-center gap-2">
                <AlertOctagon className="w-4 h-4 shrink-0" />
                {prError}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
